name: Frontend

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "8"

      - name: Install dependencies
        run: |
          cd ./assets
          yarn install

      - name: Lint
        run: |
          cd ./assets
          yarn eslint .
