name: Frontend

on:
  push:
    branches: [ dev ]
    paths: assets/src/main/**
  pull_request:
    branches: [ dev ]
    paths: assets/src/main/**

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #- name: Setup Node
        #uses: actions/setup-node@v2-beta
        #with:
          #node-version: "8"

      #- name: Install dependencies
        #run: |
          #cd assets
          #yarn install

      - name: changed files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          output: ' '
      
      - name: Lint
        run: |
          array=(${{ steps.file_changes.outputs.files }})
          matchingFiles=${array[@]/*assets/src/main/*/}
          echo matchingFiles
